Activate clang-tidy

diff --git a/.dev/pre-commit b/.dev/pre-commit
--- a/.dev/pre-commit
+++ b/.dev/pre-commit
@@ -6,6 +6,7 @@
 # it wants to stop the commit.
 #
 # To enable this hook, rename this file to "pre-commit".
+set -e
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -16,19 +17,20 @@ else
 fi
 
 # Test clang-format
-clangformatout=$(git clang-format --style=file:./.dev/.clang-format --staged -q)
+clangformatout=$(git clang-format --style=file:./.dev/.clang-format --staged)
 
 # Redirect output to stderr.
 exec 1>&2
 
-if [ "$clangformatout" != "" ]
+if [ "$clangformatout" != "clang-format did not modify any files" ] && [ "$clangformatout" != "no modified files to format" ]
+
 then
     echo "Format error!"
     echo "Use git clang-format"
     exit 1
 fi
 
-codespell=$(codespell --skip "./.git" --ignore-words ./.dev/.codespellignore --write-changes)
+codespell=$(codespell --skip "./.git" --ignore-words ./.dev/.codespellignore --write-changes )
 
 exec 1>&2
 
@@ -37,6 +39,14 @@ then
    echo "Spelling errors!"
    echo "Run codespell"
    echo $codespell
+   exit 1
+fi
+
+clangtidyout=$(git diff -U0 --no-color --cached | clang-tidy-diff-19.py -config-file=.dev/.clang-tidy -p1)
+if [ "$clangtidyout" !="No relevant changes found."]
+then
+   echo "Tidy errors"
+   echo $clangtidyout
    exit 1
 fi
 
